version: "3.8"

services:
  redis:
    container_name: redis_just_stash
    image: redis:8.4.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - just_stash_it
  api:
    container_name: api_just_stash
    image: textbin-app:latest
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - just_stash_it
    depends_on:
      - redis

  frontend:
    container_name: frontend_just_stash
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - just_stash_it
    volumes:
      - ./src/static:/usr/share/nginx/html

networks:
  just_stash_it:
    driver: bridge